spring:
  application:
    name: boardexam

  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb
    username: hwan
    password: hwan1487
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80